### PR TITLE
Added labels to deployment pod template spec

### PR DESCRIPTION
**Pull request by BardOve**
Labels field in application definition now propegate correctly to pod template in deployment.

Changes GroupKindFromControllerResource to a map instead of a function as it was essentially already functioning as one.

Uses the standard SetResourceLabelIfApplies by adding Pod to the ControllerResources and adding a map from the resource -> GroupKind.

Had to create a pod and extract the template, as PodTemplateSpec does not implement type Object, which is needed for setting labels.

### CODE REVIEW

**Review by esphen — APPROVED** [review]
Funksjonelt sett ser det greit ut, men hadde vært fint om vi fikk de-duplisert de nye labels-funksjonene etter hvert

**Review by anderssonw — COMMENTED** [review]
Does PodTemplateSpec not implement `.GetObjectKind().GroupVersionKind()`? Is there a way we can instead build a Pod object and use its Spec if not?

This seems like a circumvention of refactoring the Deployment resource generating, to avoid using already existing function

**Comment by anderssonw** [comment]
Added a fix according to what I specified. I'm not a huge fan of how this thing works, and would honestly prefer if i could somehow get all owned resources and apply it in the main controller function instead of separately for each resource. Asked in the controller-runtime slack if something like that is feasible, so we will see :)

**Review by anderssonw — APPROVED** [review]
lgtm

**Pull request merged**
